/**
 * Generates ../docker-compose.yml for the single combined image, copying all
 * runtime env from Backend/.env and applying production overrides.
 *
 *   IMAGE=user/founderkey:latest PUBLIC_URL=https://app.azurewebsites.net \
 *     node deploy/gen-compose.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT, 'Backend', '.env');
const OUT = path.join(ROOT, 'docker-compose.yml');

const IMAGE = process.env.IMAGE || 'prashanth17102/founderkey:latest';
const PUBLIC_URL = process.env.PUBLIC_URL || '';

// Parse .env (KEY=VALUE, ignore comments/blanks; keep everything after first =).
const env = {};
for (const line of fs.readFileSync(ENV_FILE, 'utf8').split(/\r?\n/)) {
  const t = line.trim();
  if (!t || t.startsWith('#')) continue;
  const i = t.indexOf('=');
  if (i === -1) continue;
  let v = t.slice(i + 1).trim();
  if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
    v = v.slice(1, -1);
  }
  env[t.slice(0, i).trim()] = v;
}

// Production overrides.
env.NODE_ENV = 'production';
env.PORT = '3000';
if (PUBLIC_URL) {
  env.FRONTEND_URL = PUBLIC_URL;
  env.ALLOWED_ORIGINS = PUBLIC_URL;
}
// App Service needs to know which port to route public traffic to (nginx :80).
env.WEBSITES_PORT = '80';
// Use the in-memory fallback unless a real Redis is provided.
if (!env.REDIS_URL) env.REDIS_URL = 'redis://localhost:6379';

const q = (s) => JSON.stringify(String(s)); // valid YAML double-quoted scalar

const lines = [
  '# Generated by deploy/gen-compose.js — single combined container (nginx + Node).',
  '# Holds all runtime env values (per request). Keep this file private; do not commit.',
  'services:',
  '  app:',
  `    image: ${IMAGE}`,
  '    restart: always',
  '    ports:',
  '      - "80:80"',
  '    environment:',
];
for (const [k, v] of Object.entries(env)) {
  lines.push(`      ${k}: ${q(v)}`);
}

fs.writeFileSync(OUT, lines.join('\n') + '\n');
console.log(`Wrote ${OUT} (${Object.keys(env).length} env vars, image ${IMAGE}, public ${PUBLIC_URL || '(unset)'})`);
